const express = require('express')
const router = express.Router()
const {auth} = require('../middlewares/authMIddleware')
const {handleRegister,handleLogin,handleRegisterLink,handleSendingUserInfo,handleCheckout,trackOrders,handleChangePassword,handleLogout,handleCancelOrder,handleSendingResetLink,handleResetLink,handleChangePhone,handleChangeName,chkResetLink} = require('../controllers/userControllers')

router.post('/register', handleRegister)
router.post('/login', handleLogin)
router.get('/register/link/:token',handleRegisterLink)
router.get('/details',auth,handleSendingUserInfo)
router.post('/checkout', auth,handleCheckout)
router.get('/track/orders',auth,trackOrders)
router.post('/change/password',auth,handleChangePassword)
router.post('/logout',auth,handleLogout)
router.post('/send/resetlink',handleSendingResetLink)
router.post('/reset/password/:token',handleResetLink)
router.get('/check/resetlink/:token',chkResetLink)
router.post('/change/phone',auth,handleChangePhone)     
router.post('/change/name',auth,handleChangeName)     
router.post('/delete/order/:id',auth,handleCancelOrder)     
module.exports = router